// #define PJMEDIA_HAS_SPEEX_AEC    0

#define PJMEDIA_HAS_OPUS_CODEC	1

#define PJMEDIA_CODEC_OPUS_DEFAULT_SAMPLE_RATE 8000

/* Enable passthrough codec framework */
#define PJMEDIA_HAS_PASSTHROUGH_CODECS	0

/* Only PCMA and PCMU are supported by WMME-direct */
#define PJMEDIA_HAS_PASSTHROUGH_CODEC_PCMU	1
#define PJMEDIA_HAS_PASSTHROUGH_CODEC_PCMA	1
#define PJMEDIA_HAS_PASSTHROUGH_CODEC_AMR	0
#define PJMEDIA_HAS_PASSTHROUGH_CODEC_G729	0
#define PJMEDIA_HAS_PASSTHROUGH_CODEC_ILBC	0


#define PJMEDIA_HAS_VIDEO	1